// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Model.AreaModels.Ctv", b =>
                {
                    b.Property<string>("CtvCode")
                        .HasColumnType("text");

                    b.Property<string>("CtvLGDCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("CtvName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("CtvCode");

                    b.HasIndex("DistrictCode");

                    b.ToTable("Ctv");

                    b.HasData(
                        new
                        {
                            CtvCode = "XVR2002",
                            CtvLGDCode = "32",
                            CtvName = "Saha",
                            DistrictCode = "XVR2002",
                            Id = 1
                        });
                });

            modelBuilder.Entity("API.Model.AreaModels.District", b =>
                {
                    b.Property<string>("DistrictCode")
                        .HasColumnType("text");

                    b.Property<string>("DistrictLGDCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DistrictCode");

                    b.HasIndex("StateCode");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            DistrictCode = "XVR2002",
                            DistrictLGDCode = "133",
                            DistrictName = "Ambala",
                            Id = 1,
                            StateCode = "XVR2002"
                        });
                });

            modelBuilder.Entity("API.Model.AreaModels.State", b =>
                {
                    b.Property<string>("StateCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StateLGDCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("StateCode");

                    b.ToTable("State");

                    b.HasData(
                        new
                        {
                            StateCode = "XVR2002",
                            Id = 1,
                            StateLGDCode = "6",
                            StateName = "Haryana"
                        });
                });

            modelBuilder.Entity("API.Model.ExceptionHandlerModels.ExceptionLog", b =>
                {
                    b.Property<string>("DataCode")
                        .HasColumnType("text");

                    b.Property<string>("ClassName")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InnerException")
                        .HasColumnType("text");

                    b.Property<string>("MethodName")
                        .HasColumnType("text");

                    b.Property<string>("OccuredAt")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("StringException")
                        .HasColumnType("text");

                    b.HasKey("DataCode");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("API.Model.ManagementModels.BankManagement.BankBranch", b =>
                {
                    b.Property<string>("BankBranchCode")
                        .HasColumnType("text");

                    b.Property<double>("AllocateStorageSize")
                        .HasColumnType("double precision");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchAddress")
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IFSC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MICR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalStorageSize")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedStorageSize")
                        .HasColumnType("double precision");

                    b.HasKey("BankBranchCode");

                    b.HasIndex("OrganizationCode");

                    b.ToTable("BankBranch");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentBankOrganizationMap", b =>
                {
                    b.Property<string>("DepartmentBankOrganizationMapCode")
                        .HasColumnType("text");

                    b.Property<string>("BankOrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepartmentOrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InputFileHeader")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMapped")
                        .HasColumnType("boolean");

                    b.HasKey("DepartmentBankOrganizationMapCode");

                    b.HasIndex("BankOrganizationCode");

                    b.HasIndex("DepartmentOrganizationCode");

                    b.ToTable("DepartmentBankOrganizationMap");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.CommodityMaster", b =>
                {
                    b.Property<string>("CommodityCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CommodityCode");

                    b.ToTable("CommodityMaster");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.Designation", b =>
                {
                    b.Property<string>("DesignationCode")
                        .HasColumnType("text");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("DesignationCode");

                    b.ToTable("Designation");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.GatePass", b =>
                {
                    b.Property<string>("GatePassCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GatePassFilePath")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IssuedByUserCode")
                        .HasColumnType("text");

                    b.Property<string>("QRCodePath")
                        .HasColumnType("text");

                    b.Property<string>("TransportRouteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GatePassCode");

                    b.HasIndex("TransportRouteCode");

                    b.ToTable("GatePass");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.Office", b =>
                {
                    b.Property<string>("OfficeCode")
                        .HasColumnType("text");

                    b.Property<double>("AllocateStorageSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalStorageSize")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedStorageSize")
                        .HasColumnType("double precision");

                    b.HasKey("OfficeCode");

                    b.HasIndex("OrganizationCode");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.TransportRoute", b =>
                {
                    b.Property<string>("TransportRouteCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActualJourneyEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ActualJourneyStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("BaseAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("Commodities")
                        .HasColumnType("jsonb");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinationStatus")
                        .HasColumnType("text");

                    b.Property<double>("DistanceInKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpectedJourneyEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpectedJourneyStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("ExpectedTravelTimeHours")
                        .HasColumnType("double precision");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<double>("OtherCharges")
                        .HasColumnType("double precision");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceOrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TollTax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalCharge")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransportRouteCode");

                    b.HasIndex("UserCode");

                    b.HasIndex("VehicleCode");

                    b.ToTable("TransportRoute");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.TransportRouteHistory", b =>
                {
                    b.Property<string>("ApprovalCode")
                        .HasColumnType("text");

                    b.Property<string>("ActionByRoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionByUserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AssignedToRoleCode")
                        .HasColumnType("text");

                    b.Property<string>("AssignedToUserCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransportRouteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ApprovalCode");

                    b.HasIndex("TransportRouteCode");

                    b.ToTable("TransportRouteHistory");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.UnitMaster", b =>
                {
                    b.Property<string>("UnitCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("UnitWeight")
                        .HasColumnType("double precision");

                    b.HasKey("UnitCode");

                    b.ToTable("UnitMaster");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.UploadFileInfo", b =>
                {
                    b.Property<string>("FileInfoCode")
                        .HasColumnType("text");

                    b.Property<string>("AcknowledgementFileName")
                        .HasColumnType("text");

                    b.Property<string>("AcknowledgementFileNamePath")
                        .HasColumnType("text");

                    b.Property<string>("BankAcknowledgementFilePath")
                        .HasColumnType("text");

                    b.Property<string>("BankBranchCode")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("BankNoAcknowledgementFilePath")
                        .HasColumnType("text");

                    b.Property<string>("BankProcessFilePath")
                        .HasColumnType("text");

                    b.Property<string>("BankResponsePath")
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentApprovalStatus")
                        .HasColumnType("text");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileNumber")
                        .HasColumnType("text");

                    b.Property<double>("FileSize")
                        .HasColumnType("double precision");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("IFSC")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InProcessFilePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("InprocessDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InternalFilePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsInternalOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("NoAcknowledgementFileName")
                        .HasColumnType("text");

                    b.Property<string>("NoAcknowledgementFileNamePath")
                        .HasColumnType("text");

                    b.Property<string>("OfficeCode")
                        .HasColumnType("text");

                    b.Property<string>("OfficeName")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer");

                    b.Property<string>("RejectFilePath")
                        .HasColumnType("text");

                    b.Property<string>("RequestFilePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ResponseFileName")
                        .HasColumnType("text");

                    b.Property<string>("ResponseFilePath")
                        .HasColumnType("text");

                    b.Property<string>("ResponseOrganizationCode")
                        .HasColumnType("text");

                    b.Property<string>("ResponseUserCode")
                        .HasColumnType("text");

                    b.Property<string>("SharedUsers")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserFileDirectoryCode")
                        .HasColumnType("text");

                    b.HasKey("FileInfoCode");

                    b.HasIndex("OrganizationCode");

                    b.HasIndex("UserCode");

                    b.ToTable("UploadFileInfo");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.UploadFileInfoHistory", b =>
                {
                    b.Property<string>("UploadFileInfoHistoryCode")
                        .HasColumnType("text");

                    b.Property<string>("ActionByRoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionByUserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AssignedToRoleCode")
                        .HasColumnType("text");

                    b.Property<string>("AssignedToUserCode")
                        .HasColumnType("text");

                    b.Property<string>("FileInfoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UploadFileInfoHistoryCode");

                    b.HasIndex("FileInfoCode");

                    b.ToTable("UploadFileInfoHistory");
                });

            modelBuilder.Entity("API.Model.ManagementModels.Organization", b =>
                {
                    b.Property<string>("OrganizationCode")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("AllocateStorageSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FetureType")
                        .HasColumnType("text");

                    b.Property<string>("GstNumber")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConversion")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationType")
                        .HasColumnType("text");

                    b.Property<string>("PanNumber")
                        .HasColumnType("text");

                    b.Property<string>("ParentOrganizationCode")
                        .HasColumnType("text");

                    b.Property<string>("PaymentAcknowledgment")
                        .HasColumnType("text");

                    b.Property<string>("PaymentFileHeader")
                        .HasColumnType("text");

                    b.Property<string>("PaymentNotAcknowledgement")
                        .HasColumnType("text");

                    b.Property<string>("PaymentResponseFileHeader")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<double>("StorageSize")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedStorageSize")
                        .HasColumnType("double precision");

                    b.HasKey("OrganizationCode");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.DriverDetails", b =>
                {
                    b.Property<string>("DriverDetailCode")
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DriverName")
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContact")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LicenseExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<string>("LicenseType")
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DriverDetailCode");

                    b.HasIndex("UserCode");

                    b.ToTable("DriverDetails");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.Vehicle", b =>
                {
                    b.Property<string>("VehicleCode")
                        .HasColumnType("text");

                    b.Property<double>("CapacityInTons")
                        .HasColumnType("double precision");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Createdby")
                        .HasColumnType("text");

                    b.Property<double>("FuelTankCapacityInLiters")
                        .HasColumnType("double precision");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GPSDeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RCNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatePerKm")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("integer");

                    b.HasKey("VehicleCode");

                    b.HasIndex("OrganizationCode");

                    b.HasIndex("VehicleTypeCode");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.VehicleDriverMap", b =>
                {
                    b.Property<string>("VehicleDriverMapCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DriverDetailCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UnassignedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VehicleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleDriverMapCode");

                    b.HasIndex("DriverDetailCode");

                    b.HasIndex("VehicleCode");

                    b.ToTable("VehicleDriverMap");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.VehicleType", b =>
                {
                    b.Property<string>("VehicleTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("MaxLoadCapacity")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleTypeCode");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserFileDirectory", b =>
                {
                    b.Property<string>("UserFileDirectoryCode")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentDirectoryCode")
                        .HasColumnType("text");

                    b.HasKey("UserFileDirectoryCode");

                    b.ToTable("UserFileDirectory");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.Administor", b =>
                {
                    b.Property<string>("AdministorCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdministorCode");

                    b.HasIndex("OrganizationCode");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserCode");

                    b.ToTable("Administor");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.BankUser", b =>
                {
                    b.Property<string>("BankUserCode")
                        .HasColumnType("text");

                    b.Property<string>("BankBranchCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DesignationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalStorageSize")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedStorageSize")
                        .HasColumnType("double precision");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BankUserCode");

                    b.HasIndex("BankBranchCode");

                    b.HasIndex("DesignationCode");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserCode");

                    b.ToTable("BankUser");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.DepartmentUser", b =>
                {
                    b.Property<string>("DepartmentUserCode")
                        .HasColumnType("text");

                    b.Property<string>("DesignationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalStorageSize")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedStorageSize")
                        .HasColumnType("double precision");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentUserCode");

                    b.HasIndex("DesignationCode");

                    b.HasIndex("OfficeCode");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserCode");

                    b.ToTable("DepartmentUser");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.TransporterUser", b =>
                {
                    b.Property<string>("TransportUserCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDriver")
                        .HasColumnType("boolean");

                    b.Property<string>("OrganizationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalStorageSize")
                        .HasColumnType("double precision");

                    b.Property<double>("UsedStorageSize")
                        .HasColumnType("double precision");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransportUserCode");

                    b.HasIndex("OrganizationCode");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserCode");

                    b.ToTable("TransporterUser");
                });

            modelBuilder.Entity("API.Model.Menus.Menu", b =>
                {
                    b.Property<string>("MenuCode")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("MenuCode");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("API.Model.Menus.MenuAccess", b =>
                {
                    b.Property<string>("AccessCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("AccessCode");

                    b.HasIndex("MenuCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("MenuAccess");
                });

            modelBuilder.Entity("API.Model.Routes.Route", b =>
                {
                    b.Property<string>("RouteCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParentCode")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("RouteCode");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("API.Model.Routes.RouteAccess", b =>
                {
                    b.Property<string>("AccessCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("AccessCode");

                    b.HasIndex("RoleCode");

                    b.HasIndex("RouteCode");

                    b.ToTable("RouteAccess");
                });

            modelBuilder.Entity("API.Model.UserModels.RoleAccess", b =>
                {
                    b.Property<string>("AccessId")
                        .HasColumnType("text");

                    b.Property<bool>("AccessToRole")
                        .HasColumnType("boolean");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccessId");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserCode");

                    b.ToTable("RoleAccess");
                });

            modelBuilder.Entity("API.Model.UserModels.User", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CtvCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEntityUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserCode");

                    b.HasIndex("CtvCode");

                    b.ToTable("User");
                });

            modelBuilder.Entity("API.Model.UserModels.UserLogin", b =>
                {
                    b.Property<string>("LoginCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Latitude")
                        .HasColumnType("text");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Longitude")
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginCode");

                    b.HasIndex("UserCode");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("API.Model.UserModels.UserRole", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleType")
                        .HasColumnType("text");

                    b.HasKey("RoleCode");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            RoleCode = "XVR2002",
                            Id = 1,
                            RoleLevel = 7,
                            RoleName = "Supreme"
                        });
                });

            modelBuilder.Entity("API.Model.AreaModels.Ctv", b =>
                {
                    b.HasOne("API.Model.AreaModels.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("API.Model.AreaModels.District", b =>
                {
                    b.HasOne("API.Model.AreaModels.State", "State")
                        .WithMany()
                        .HasForeignKey("StateCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("API.Model.ManagementModels.BankManagement.BankBranch", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentBankOrganizationMap", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "BankOrganization")
                        .WithMany()
                        .HasForeignKey("BankOrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.ManagementModels.Organization", "DepartmentOrganization")
                        .WithMany()
                        .HasForeignKey("DepartmentOrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankOrganization");

                    b.Navigation("DepartmentOrganization");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.GatePass", b =>
                {
                    b.HasOne("API.Model.ManagementModels.DepartmentManagement.TransportRoute", "TransportRoute")
                        .WithMany()
                        .HasForeignKey("TransportRouteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportRoute");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.Office", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.TransportRoute", b =>
                {
                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.ManagementModels.TransporterManagement.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.TransportRouteHistory", b =>
                {
                    b.HasOne("API.Model.ManagementModels.DepartmentManagement.TransportRoute", "TransportRoute")
                        .WithMany()
                        .HasForeignKey("TransportRouteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransportRoute");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.UploadFileInfo", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Model.ManagementModels.DepartmentManagement.UploadFileInfoHistory", b =>
                {
                    b.HasOne("API.Model.ManagementModels.DepartmentManagement.UploadFileInfo", "UploadFileInfo")
                        .WithMany()
                        .HasForeignKey("FileInfoCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadFileInfo");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.DriverDetails", b =>
                {
                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.Vehicle", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.ManagementModels.TransporterManagement.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("API.Model.ManagementModels.TransporterManagement.VehicleDriverMap", b =>
                {
                    b.HasOne("API.Model.ManagementModels.TransporterManagement.DriverDetails", "DriverDetail")
                        .WithMany()
                        .HasForeignKey("DriverDetailCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.ManagementModels.TransporterManagement.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverDetail");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.Administor", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.BankUser", b =>
                {
                    b.HasOne("API.Model.ManagementModels.BankManagement.BankBranch", "BankBranch")
                        .WithMany()
                        .HasForeignKey("BankBranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.ManagementModels.DepartmentManagement.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankBranch");

                    b.Navigation("Designation");

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.DepartmentUser", b =>
                {
                    b.HasOne("API.Model.ManagementModels.DepartmentManagement.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.ManagementModels.DepartmentManagement.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Designation");

                    b.Navigation("Office");

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.ManagementModels.UserModels.TransporterUser", b =>
                {
                    b.HasOne("API.Model.ManagementModels.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.Menus.MenuAccess", b =>
                {
                    b.HasOne("API.Model.Menus.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.Routes.RouteAccess", b =>
                {
                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.Routes.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.UserModels.RoleAccess", b =>
                {
                    b.HasOne("API.Model.UserModels.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("API.Model.UserModels.User", b =>
                {
                    b.HasOne("API.Model.AreaModels.Ctv", "Ctv")
                        .WithMany()
                        .HasForeignKey("CtvCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ctv");
                });

            modelBuilder.Entity("API.Model.UserModels.UserLogin", b =>
                {
                    b.HasOne("API.Model.UserModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
